Farmers_Portal/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^',  include("home.urls", namespace="home")),
    url(r'^',  include("User.urls", namespace="user")),
    url(r'^',  include("location.urls", namespace="location")),
    url(r'^posts/',  include("post.urls", namespace="post")),
    url(r'^crops/',  include("crop.urls", namespace="crop")),
    url(r'^admin/', admin.site.urls),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

User/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^login/$', views.check_login, name="login"),
    url(r'^signup/$', views.signup_user, name="signup"),
    url(r'^logout/$', views.logout_user, name="logout"),
    url(r'^profile/$', views.view_profile, name="profile"),
]

crop/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^register$', views.register_crop, name="register"),
    url(r'^view/$', views.view_crops, name="detail"),
    url(r'^delete/(?P<id>\d+)/$', views.crop_delete, name="delete"),
	url(r'^tag_disease/(?P<id>\d+)/$', views.tag_disease, name="disease"),
	url(r'^tag_disease/(?P<id>\d+)/crop/(?P<crop_id>\d+)$', views.tag_disease, name="disease"),
]

location/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^location/(?P<id>\d+)/$', views.weather_query, name = "weather"),
]

location/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Location(models.Model):
	loc_id = models.AutoField(primary_key=True)
	city = models.CharField(max_length=30)
	state = models.CharField(max_length=30)

	def __unicode__(self):
		return self.city + ', ' + self.state
	def __str__(self):
		return self.city + ', ' + self.state

class Weather(models.Model):
	wea_id = models.AutoField(primary_key=True)
	temperature = models.IntegerField()
	humidity = models.IntegerField()
	date_record = models.DateField()
	location = models.ForeignKey(Location, on_delete=models.CASCADE)

	def __unicode__(self):
		return str(self.location) + ', ' + str(self.wea_id)
	def __str__(self):
		return str(self.location) + ', ' + str(self.wea_id)

location/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages

from django.db import connection, transaction

from User.models import check_if_auth_user

from collections import namedtuple

def namedtuplefetchall(cursor):
	"Return all rows from a cursor as a namedtuple"
	desc = cursor.description
	nt_result = namedtuple('Result', [col[0] for col in desc])
	return [nt_result(*row) for row in cursor.fetchall()]

# Create your views here.

def weather_query(request, id):
	check = check_if_auth_user(request)
	current_user = None
	if check:
		cursor = connection.cursor()
		if request.session["user_class"] == 'E':
			query = "SELECT * FROM User_expert WHERE `User_expert`.'user_id' = %s"
		else:
			query = "SELECT * FROM User_farmer WHERE `User_farmer`.'user_id' = %s"

		cursor.execute(query, [check, ])
		result = namedtuplefetchall(cursor)
		current_user = result[0]

	if current_user is None:
		messages.error(request, "Perform Login first")
		return redirect("home:welcome")

	if request.session["user_class"] == 'F':
		messages.error(request, "Sorry, only experts are allowed to study location's weather.")
		return redirect("home:welcome")

	query = "SELECT * FROM location_location WHERE `location_location`.loc_id = %s"
	cursor.execute(query, [id, ])
	result = namedtuplefetchall(cursor)

	if not result:
		messages.error(request, "Such location doesn't exist.")
		return redirect("home:welcome")

	location = result[0]

	query = "SELECT * FROM location_weather WHERE `location_weather`.'location_id' = %s ORDER BY `location_weather`.'date_record' DESC"
	cursor.execute(query, [id, ])
	result = namedtuplefetchall(cursor)

	context_data = {
		"user": current_user,
		"location": location,
		"weather_info": result[:10], # Only recent 10 records will be shown
	}
	return render(request, "location.html", context_data)

templates/aboutus.html
{% extends "base.html" %}
{% load staticfiles %}
{% block navbar %}
	{% if user %}
		{% include "navbar_after_login.html" %}
	{% else %}
		{% include "navbar_before_login.html" %}
	{% endif %}

{% endblock navbar %}

{% block content %}
	<div class="container">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="caption">
						<h2 align="center">Meet Our Team</h2>
						<br><br>

<div class="row" >
					<div class="col-sm-4">
						<img id="team" style="width:100%;height:50%;border-radius:50%;" alt="Arjav Jain" src="{% static 'images/arjav.jpeg'%}">
						<p></p>
						<p>I am Fuled by my Passion for unserstanding the new Technologies.
						I consider myself forever a student.eager to both build on my academic
						Foundations and stay in tune with the latest concept of little experiments
						around the corner</p>
					</div>
					<div class="col-sm-4">
						<img id="team" style="width:100%;height:50%;border-radius:50%;" alt="Varnit Jindal" src="{% static 'images/varnit.jpeg'%}">
						<p>My Hunger for Knowledge and determination to turn information into
							action has contributed to my most recent sucess. Working on Technology
							with increase the opportunity for growth and personal Growth.
							.</p>
					</div>
					<div class="col-sm-4">
						<img id="team" style="width:100%;height:50%;border-radius:50%;" alt="Amar Aggarwal" src="{% static 'images/amar.jpeg'%}">
						<p>Good in Artificial intelligency and security Keep observer a,inovative
							adoptive.Fast Learner infulencer.Passionate about data science and
							problem Solving. Highly capable leader and well Organised.</p>
					</div>
						
					</div>

				</div>
				
			</div>
	
	</div>
	
{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Farmers' Portal</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	{% block add_static %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>
 	{% endblock add_static %}
</head>
<body>
	{% block navbar %}
			{% include "navbar_before_login.html" %}
	{% endblock navbar %}

	{% include "messages_display.html" %}
	

	{% block content %}
	
	{% endblock content %}

    {% block afterbody %}
	<br>
	<footer class="footer">
	<br>
      <div class="container">
        <p class="text-muted" align="center"><a href="#top"><span class="glyphicon glyphicon-arrow-up"></span> Back to Top</a></p>
        <p class="text-muted" align="center"><a href="/"><span class="glyphicon glyphicon-home"></span> Home</a></p>
      </div>
    </footer>
	{% endblock afterbody %}
	
</body>
</html>

templates/create_edit_post.html
{% extends "base.html" %}

{% block content %}
	<div class="container siteForm">
	{% if post_obj %}
		<h2 class="heading">Edit your post here!</h2>
	{% else %}
		<h2 class="heading">Enter details of your new Post!</h2>
	{% endif %}
	
	<div class="row">
		<div class="col-lg-2"></div>
		<div class="col-lg-8">
			<form role="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
				<div class="form-group">
					<input class="form-control FormElement" type="text" name="post_title" required="True" placeholder="What is this post about?" value="{{ post_obj.title }}">
				</div>
				<div class="form-group">
					<textarea class="form-control FormElement" name="post_disc" required="True" placeholder="Describe your post" rows="6">{{ post_obj.description }}</textarea>
				</div>
				<div class="form-group" style="text-align:center;">
				 <label for="category">Choose category</label>
				  <select class="form-control" id="category" name="post_category">
				    {% for key,value in category.items %}
				    	<option>{{ value }}</option>
				    {% endfor %}
				  </select>
					<!--<input class="form-control FormElement" type="text" name="item_category" required="True" placeholder="Choose your category"><-->
				</div>
				<div class="form-group">
						<div class="panel panel-default">
							<div class="panel-heading">Upload the concerned image</div>
							<div class="col-lg-6 col-lg-offset-3">			
								<div class="panel-body"><div><input type="file" class="form-control" name="post_image"></div></div>
							</div>
						</div>
				</div><br>
				<button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
			</form>	
		</div>
	</div>

	</div>
	<br>	
{% endblock content %}

templates/faq.html
{% extends "base.html" %}
{% load staticfiles %}
{% block navbar %}
	{% if user %}
		{% include "navbar_after_login.html" %}
	{% else %}
		{% include "navbar_before_login.html" %}
	{% endif %}

{% endblock navbar %}

{% block content %}
	<div class="container">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="caption">
						<h2 align="center">FAQ</h2>
						<br><br>
						<p><b>Q. What is Farmers' Portal?</b></p>
						<p><b>A. </b>The Farmers' Portal is a web portal to connect farmers and experts. Experts can help farmers deal with various agricultural problems.</p>
						<br>
						<p><b>Q. How to start using this portal?</b></p>
						<p><b>A. </b>Experts and Farmers can both register themselves using the sign up form. After signing up, you may login and start working.</p>
						<br>
						<p><b>Q. What facilities are available in this portal for a farmer?</b></p>
						<p><b>A. </b>A farmer can register his/her crop for maintenance. He can search for other farmers in his/her location. Most importantly, he/she can post a question to experts regarding farming. Also, if farmer is facing a crop disease, he/she can take expert's advice. Many more options available.</p>
						<br>
						<p><b>Q. What can an expert expect in this site?</b></p>
						<p><b>A. </b>An Expert, after successful registration, can study various crops/infected crops in any location. He may study the crops grown by other farmers and help them accordingly. He may also study weather info for some farmer's location.</p>
						<br>
						<p><b>Q. I am a farmer and my crop is infected. What should I do??</b></p>
						<p><b>A. </b>Simply make a new post about this. During making a new post, ensure that you upload a good photo describing the infection in the crop. After the post is created, an expert will respond accordingly.</p>
					</div>

				</div>
				
			</div>
	
	</div>
	
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block navbar %}
	{% if user %}
		{% include "navbar_after_login.html" %}
	{% else %}
		{% include "navbar_before_login.html" %}
	{% endif %}

{% endblock navbar %}

{% block content %}
	<div class="container">
	
	{% if user %}
		<div class="row">
			{% if user_class == 'F' %}
						<div class="col-lg-6">
			{% else %}
				<div class="col-lg-4">
			{% endif %}
				<ul class="list-group menu">
					<li class="list-group-item" align="center">Posts and Crops</li>
					<a href="/posts/create"><li class="list-group-item">Create a new post</li></a>
					{% if user_class == 'F' %}
						<a href="/crops/register"><li class="list-group-item">Register a new crop</li></a>
						<a href="/crops/view"><li class="list-group-item">View your crops</li></a>
					{% else %}
						<a href="#"><li class="list-group-item"><strike>Register a new crop</strike></li></a>
						<a href="#"><li class="list-group-item"><strike>View your crops</strike></li></a>
					{% endif %}
					
					
				</ul>
				
			</div>
			{% if user_class == 'E' %}
				<div class="col-lg-4">
					<ul class="list-group menu">
						<li class="list-group-item" align="center">search</li>
						<a href="/query/1"><li class="list-group-item">Search for some farmer</li></a>
						<a href="/query/2"><li class="list-group-item">Find some post</li></a>
						<a href="/query/3"><li class="list-group-item">Find some crop</li></a>
					</ul>
				</div>
				<div class="col-lg-4">
					<ul class="list-group menu">
						<li class="list-group-item" align="center">Information</li>
						<a href="/query/4"><li class="list-group-item">View farmers of your location</li></a>
						<a href="/query/5"><li class="list-group-item">View infected crops</li></a>
						<a href="/query/6"><li class="list-group-item">See nutrients and associated fertilizers</li></a>
					</ul>
				</div>
			{% else %}
				<div class="col-lg-6">
				<ul class="list-group menu">
					<li class="list-group-item" align="center">search</li>
					<a href="/query/1"><li class="list-group-item">Search for some farmer</li></a>
					<a href="/query/2"><li class="list-group-item">Find some post</li></a>
					<a href="/query/3"><li class="list-group-item">Find some crop</li></a>
				</ul>
				</div>
			{% endif %}
			

		</div>
	{% else %}
		<div class="jumbotron">
		<h1>Welcome to Farmers' Portal</h1>
		<p>A web portal to connect farmers and experts.
		<ul>
		    <li>Being a farmer, register your crops, maintain your crops, search for other farmers, etc.</li>
		    <li>Being an expert, study infected crops, know what other farmers are growing, advice farmers, etc.</li>
		    <li>Create posts and talk to farmers / experts.</li>
		</ul>
		</p>
		<p><a class="btn btn-primary btn-lg" href="/faq" role="button">Learn more</a> <a class="btn btn-primary btn-lg" href="/signup" role="button">Register</a></p>
		</div>
	{% endif %}

	
	<h1 class="heading">P O S T S</h1>
	<div class="row" align="center">
		{% for obj in all_posts %}
			<div class="col-lg-4">
			<div class="panel panel-default">
				
				{% if obj.author_expert_id %}
					<div class="panel-heading" style="background: url('{% static 'images/post_head_expert_back.jpg' %}') repeat;"><b>EXPERT'S POST</b></div>
				{% else %}
					<div class="panel-heading" ><b>FARMER'S POST</b></div>
				{% endif %}
				<div class="panel-body">
					<a href="{% url 'post:detail' id=obj.post_id %}"><img src="/media/{{obj.image}}" alt="No image uploaded" style="width: 80%; height: 180px"></a>
					<div class="caption">
						<p align="center"> Posted {{ obj.timestamp|timesince }} ago </p>
						<h4 align="center">{{ obj.title }}</h4>
						<!-- <p align="justify">{{ obj.description|linebreaks|truncatechars:80 }}</p> -->
						<p align="center"><a href="{% url 'post:detail' id=obj.post_id %}" class="btn btn-primary" role="button">View Post</a></p>
					</div>
				</div>
			</div>
			</div>
			{% cycle "" "" "</div><div class='row'>" %}
		{% endfor %}
	</div>
	
	</div>
	<script>!function(e,t,a){var c=e.head||e.getElementsByTagName("head")[0],n=e.createElement("script");n.async=!0,n.defer=!0, n.type="text/javascript",n.src=t+"/static/js/chat_widget.js?config="+JSON.stringify(a),c.appendChild(n)}(document,"https://app.engati.com",{bot_key:"0ef503d75400401c",welcome_msg:true,branding_key:"default",server:"https://app.engati.com",e:"p" });</script>
{% endblock content %}

templates/location.html
{% extends "base.html" %}
{% block navbar %}
	{% if user %}
		{% include "navbar_after_login.html" %}
	{% else %}
		{% include "navbar_before_login.html" %}
	{% endif %}

{% endblock navbar %}

{% block content %}
	<div class="container">
	<div class="col-lg-10 col-lg-offset-1">
	<div class="panel panel-default">
		<div class="panel-heading" align="center"><h3 align="center">Location: {{ location.city }}, {{ location.state }}</h3></div>
		<div class="panel-body">
			<div class="caption">
				<br>
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Date</th>
							<th>Temperature (degree C)</th>
							<th>Humidity (%)</th>
						</tr>
					</thead>
					<tbody>
						{% for weather in weather_info %}
							<tr>
							<td>{{ weather.date_record }}</td>
							<td>{{ weather.temperature }}</td>
							<td>{{ weather.humidity }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				
			</div>
		</div>
	</div>
	</div>
	
	</div>
	
{% endblock content %}

templates/messages_display.html
{% if messages %}
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Message</h4>
        </div>
        <div class="modal-body">
		<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
	    	{% if "html_safe" in message.tags%}
	    		<p>{{ message|safe }}</p>
	    	{% else %}
	    		<p>{{ message }}</p>
	    	{% endif %}
	    </li>
	    {% endfor %}
		</ul>         
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  
</div>
<script type="text/javascript">
    $(window).load(function(){
        $('#myModal').modal('show');
    });
</script>
{% endif %}

templates/navbar_after_login.html
{% load staticfiles %}
<div class="container" id="top">
	<div class="main_image"></div>
	<div class ="heading"><h2>Farmers' Portal : <i>Connecting farmers and experts</i></h2></div>
	<nav class="navbar navbar-inverse">		
		<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>                        
		</button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
		<ul class="nav nav-tabs nav-justified">	
		<li><a href="/"><span class="glyphicon glyphicon-home"></span> <b>Home</b></a></li>
		<li><a href="/profile"><span class="glyphicon glyphicon-user"></span> <b>View your profile</b></a></li>
	    <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> <b>Logout</b></a></li>
	    <li><a href="/faq"><span class="glyphicon glyphicon-info-sign"></span> <b>FAQ</b></a></li>
	    <li><a href="/aboutus"><span class="glyphicon glyphicon-tasks"></span> <b>About Us</b></a></li>
	    </ul>
	</div>
	</nav>
</div>

templates/navbar_before_login.html
{% load staticfiles %}
<div id="loginModal" class="modal fade" role="dialog">
		<div class="modal-dialog">
	    	<!-- Modal content-->
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal">&times;</button>
		        <h4 align="center" class="modal-title"><b style="font:serif;color: #004d00;">LOGIN</b></h4>
		      </div>
		      <div class="modal-body">
		        <form role="form" action="/login/" method="post">{% csrf_token %}
		        <div class="form-group">
		        	<input class="form-control" required="True" type="email" name="email" placeholder="Email"></input></div>
		        <div class="form-group">
		        	<input class="form-control" required="True" type="password" name="passwd" placeholder="Password"></input></div>
		        <input class="btn btn-primary" type="submit" value="Login"></input>
		        
		        </form>
		      </div>
		      <div class="modal-footer">
		      	<div class="pull-left">
		        <a href="/signup"><button type="button" class="btn btn-primary btn-sm">Forgot Password</button>
		        </a></div>
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		      </div>
		    </div>
		</div>
	</div>
<div class="container" id="top">
<div class="main_image"></div>
<div class ="heading"><h2>Farmers' Portal : <i>Connecting farmers and experts</i></h2></div>
<nav class="navbar navbar-inverse">		
	<div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>                        
	</button>
  
</div>
<div class="collapse navbar-collapse" id="myNavbar">
	<ul class="nav nav-tabs nav-justified">
	<li><a href="/"><span class="glyphicon glyphicon-home"></span> <b>Home</b></a></li>
	<li><a href="/signup"><span class="glyphicon glyphicon-user"></span> <b>Sign Up</b></a></li>
    <li><a data-toggle="modal" data-target="#loginModal"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    <li><a href="/faq"><span class="glyphicon glyphicon-info-sign"></span> <b>FAQ</b></a></li>
    <li><a href="/aboutus"><span class="glyphicon glyphicon-tasks"></span> <b>About Us</b></a></li>
    </ul>
</div>
</nav>
</div>

templates/query.html
{% extends "base.html" %}
{% load staticfiles %}
{% block navbar %}
	{% if user %}
		{% include "navbar_after_login.html" %}
	{% else %}
		{% include "navbar_before_login.html" %}
	{% endif %}

{% endblock navbar %}

{% block content %}
	<div class="container">
	<div class="col-lg-10 col-lg-offset-1">
	<div class="panel panel-default">
		<div class="panel-heading" align="center"><h3 align="center">
		{% if query_id == '1' %}
			Search for some farmer
		{% elif query_id == '2' %}
			Find some post
		{% elif query_id == '3' %}
			Find some crop
		{% elif query_id == '4' %}
			View farmers of your area
		{% elif query_id == '5' %}
			View infected crops
		{% elif query_id == '6' %}
			See nutrients and associated fertilizers
		{% endif %}

		</h3></div>
		<div class="panel-body">
			<div class="caption">
				
				<p align="justify">
					{% if query_id == '1' %}
						Enter partial / full name of farmer you wish to search. You can also enter partial / full name of the farmer's city/state.
					{% elif query_id == '2' %}
						Search for any post here. You can search post titles, descriptions, and absolute IDs.
					{% elif query_id == '3' %}
						Search for any crop here. You can search crop names and their families.
					{% elif query_id == '4' %}
						Here all the farmers currently registered in your location are listed.
					{% elif query_id == '5' %}
						View all the crops that are currently infected with some kind of disease.
					{% elif query_id == '6' %}
						Here, all nutrients and fertilizers are listed.
					{% endif %}
				</p>
				{% if query_id < '4' %}
				<div class="container-fluid searchbox">
				<div align="center">
					<form class="navbar-form" role="search" action="/query/search/{{ query_id }}" method="get">
						<div class="input-group">
						<input type="text" class="form-control input-lg" placeholder="Search" name="search_query">
						<div class="input-group-btn">
						<button class="btn btn-default btn-lg" type="submit"><i class="glyphicon glyphicon-search"></i></button>
						</div>
						</div>
					</form>
				</div>
				</div>
				{% endif %}
				<br>
				{% if result %}
				<table class="table table-hover">
					<thead>
						<tr>
							{% for header in result_header %}
								<th>{{ header }}</th>
							{% endfor %}
						</tr>
					</thead>
					<tbody>
						{% for obj in result %}
							{% if query_id == '1' %}
								<tr>
									<td>{{ obj.Name }}</td>
									<td>{{ obj.Email }}</td>
								</tr>
							{% elif query_id == '2' %}
								<tr>
									<td>{{ obj.Title }}</td>
									<td>{{ obj.PostedOn }}</td>
									<td><a style="color: blue;" href="/posts/{{ obj.Link }}">Click here</a></td>
								</tr>
							{% elif query_id == '3' %}
								<tr>
									<td>{{ obj.CropName }}</td>
									<td>{{ obj.Family }}</td>
								</tr>
							{% elif query_id == '4' %}
								<tr>
									<td>{{ obj.Name }}</td>
									<td>{{ obj.Email }}</td>
								</tr>
							{% elif query_id == '5' %}
								<tr>
									<td>{{ obj.CropName }}</td>
									<td>{{ obj.Family }}</td>
									<td>{{ obj.FarmerName }}</td>
									<td>{{ obj.Email }}</td>
									<td>{{ obj.Disease }}</td>
									<td>{{ obj.Category }}</td>
								</tr>
							{% elif query_id == '6' %}
								<tr>
									<td>{{ obj.Fertilizer }}</td>
									<td>{{ obj.Nutrient }}</td>
									<td>{{ obj.NutrientType }}</td>
								</tr>
							{% endif %}
							
						{% endfor %}
					</tbody>
				</table>
				
				{% if query_id == '3' %}
				<br>
					<table class="table table-hover">
					<h4>Farmers growing this crop are listed as:</h4>
					<tbody>
					{% for obj in result_farmers %}							
						<tr>
							<td>{{ obj.name }}</td>
							<td>{{ obj.user_id }}</td>
						</tr>
					{% endfor %}
					</tbody>
					</table>
				{% endif %}
				
				{% endif %}
		
				
			</div>
		</div>
	</div>
	</div>
	</div>
	
{% endblock content %}

templates/register_crop.html
{% extends "base.html" %}

{% block content %}

<div class="container siteForm">
		<h2 class="heading">Register you crop here.</h2>
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
				<form role="form" action="/crops/register" method="post">{% csrf_token %}
					<div class="form-group" style="text-align:center;">
					 <label for="category"><br>Choose a crop.</label>
					  <select class="form-control" id="category" name="crop_name">
					    {% for crop in crop_names %}
				    		<option>{{ crop }}</option>
				   		{% endfor %}
					  </select>
					</div>

					<div class="form-group">
						<input class="form-control" type="text" name="crop_remark" placeholder="Any comments?">
					</div>
					<div class="buttonAlign">
						<button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
					</div>
				</form>	
			</div>
		</div>

	</div>
	<br>
	
{% endblock content %}